/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import { FunctionFragment, Result } from '@ethersproject/abi';
import { Listener, Provider } from '@ethersproject/providers';
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from './common';

export interface SanctionsInterface extends utils.Interface {
  contractName: 'Sanctions';
  functions: {
    'getSanctionsContract()': FunctionFragment;
    'isSanctionCheckDisabled()': FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'getSanctionsContract', values?: undefined): string;
  encodeFunctionData(functionFragment: 'isSanctionCheckDisabled', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'getSanctionsContract', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'isSanctionCheckDisabled', data: BytesLike): Result;

  events: {};
}

export interface Sanctions extends BaseContract {
  contractName: 'Sanctions';
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SanctionsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getSanctionsContract(overrides?: CallOverrides): Promise<[string]>;

    isSanctionCheckDisabled(overrides?: CallOverrides): Promise<[boolean]>;
  };

  getSanctionsContract(overrides?: CallOverrides): Promise<string>;

  isSanctionCheckDisabled(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    getSanctionsContract(overrides?: CallOverrides): Promise<string>;

    isSanctionCheckDisabled(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getSanctionsContract(overrides?: CallOverrides): Promise<BigNumber>;

    isSanctionCheckDisabled(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getSanctionsContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isSanctionCheckDisabled(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
