/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import { Provider } from '@ethersproject/providers';
import type { ERC20AssetPool, ERC20AssetPoolInterface } from '../ERC20AssetPool';

const _abi = [
  {
    inputs: [],
    name: 'assetDecimals',
    outputs: [
      {
        internalType: 'uint8',
        name: '',
        type: 'uint8',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'assetName',
    outputs: [
      {
        internalType: 'string',
        name: '',
        type: 'string',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'assetSymbol',
    outputs: [
      {
        internalType: 'string',
        name: '',
        type: 'string',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'assetType',
    outputs: [
      {
        internalType: 'string',
        name: '',
        type: 'string',
      },
    ],
    stateMutability: 'pure',
    type: 'function',
  },
];

export class ERC20AssetPool__factory {
  static readonly abi = _abi;
  static createInterface(): ERC20AssetPoolInterface {
    return new utils.Interface(_abi) as ERC20AssetPoolInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ERC20AssetPool {
    return new Contract(address, _abi, signerOrProvider) as ERC20AssetPool;
  }
}
