/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import { Provider } from '@ethersproject/providers';
import type { IHasher3, IHasher3Interface } from '../IHasher3';

const _abi = [
  {
    inputs: [
      {
        internalType: 'uint256[3]',
        name: 'data',
        type: 'uint256[3]',
      },
    ],
    name: 'poseidon',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'pure',
    type: 'function',
  },
];

export class IHasher3__factory {
  static readonly abi = _abi;
  static createInterface(): IHasher3Interface {
    return new utils.Interface(_abi) as IHasher3Interface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IHasher3 {
    return new Contract(address, _abi, signerOrProvider) as IHasher3;
  }
}
