name: build

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: echo "@mystikonetwork:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> $HOME/.npmrc
      - run: curl -LSfs get.zokrat.es | sh
      - run: echo "$HOME/.zokrates/bin" >> $GITHUB_PATH
      - run: npm install --global lerna
      - run: cp packages/mystiko-contracts/.env.example packages/mystiko-contracts/.env
      - run: lerna bootstrap
      - run: lerna run build
      - run: lerna run lint
      - run: lerna run test
      - run: lerna run deploy --scope @mystikonetwork/contracts
      - run: git diff --quiet || (echo "some generated files are not included in repo" && exit 1)
      - name: Report @mystikonetwork/utils test coverage
        uses: ArtiomTr/jest-coverage-report-action@v2.0.3
        with:
          working-directory: ./packages/mystiko-utils
          coverage-file: ./coverage/report.json
          base-coverage-file: ./coverage/report.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
      - name: Report @mystikonetwork/config test coverage
        uses: ArtiomTr/jest-coverage-report-action@v2.0.3
        with:
          working-directory: ./packages/mystiko-config
          coverage-file: ./coverage/report.json
          base-coverage-file: ./coverage/report.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
      - name: Report @mystikonetwork/protocol test coverage
        uses: ArtiomTr/jest-coverage-report-action@v2.0.3
        with:
          working-directory: ./packages/mystiko-protocol
          coverage-file: ./coverage/report.json
          base-coverage-file: ./coverage/report.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
      - name: Report @mystikonetwork/client test coverage
        uses: ArtiomTr/jest-coverage-report-action@v2.0.3
        with:
          working-directory: ./packages/mystiko-client
          coverage-file: ./coverage/report.json
          base-coverage-file: ./coverage/report.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
      - name: Telegram Failure Notification
        uses: appleboy/telegram-action@master
        if: failure()
        with:
          message: ❗ Build failed for [${{ github.repository }}](https://github.com/${{ github.repository }}/actions) because of ${{ github.actor }}
          format: markdown
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      - name: Telegram Success Notification
        uses: appleboy/telegram-action@master
        if: success()
        with:
          message: Build succeeded for [${{ github.repository }}](https://github.com/${{ github.repository }}/actions)
          format: markdown
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
